project:
  type: website
  output-dir: docs

website:
  title: "Wenyu Liu"
  navbar:
    pinned: true

    left:
      - text: "Home"
        href: "index.qmd"
      - text: "CV"
        href: "CV/index.qmd"
      - text: "Journey"
        href: "journey/index.qmd"
      - text: "Blog"
        href: blog/index.qmd
      # - text: "Research"
      #   file: research/index.qmd
      # - text: "Teaching"
      #   href: "teaching/index.qmd"
      # - text: "Talks"
      #   href: "talks/index.qmd"
      # - text: "Now"
      #   href: now/index.qmd
      # - text: "Uses"
      #   file: uses/index.qmd
    
    right:
      - text: "<i class='bi bi-person-circle' title='EPFL Directory'></i>"
        href: "https://people.epfl.ch/wenyu.liu/?lang=en"
        rel: me
      - text: "<i class='bi-envelope' title='E-mail'></i>"
        href: "mailto:wenyu.liu@epfl.ch"
        rel: me
      - text: "<i class='bi-github' title='GitHub'></i>"
        href: "https://github.com/LWYohann"
        rel: me
      - text: "<i class='bi-linkedin' title='LinkedIn'></i>"
        href: "https://www.linkedin.com/in/wenyu-liu-epfl"
        rel: me
      - text: "<i class='bi-instagram' title='Instagram'></i>"
        href: "https://www.instagram.com/lwyohann/?igsh=dmU1aTR6dW41MXFq"
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block"> <i class="bi bi-c-circle"></i>  2025 Wenyu Liu  </span>
      <span class="faux-block">All content licensed under [ CC BY 4.0 ](https://creativecommons.org/licenses/by/4.0/)</span>      
    right: |
      <span class="faux-block">Built using resources from [Andrew Heiss](https://www.andrewheiss.com/)</span>
      <span class="faux-block">Made with Quarto: [View Source <i class="bi bi-github"></i>]({{< var github-url >}})</span>

format:
  html:
    theme: 
      - html/ath.scss

    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai


